"""add password_changed_at to user

Revision ID: 0e2354fdd4d7
Revises: 82c36cf03a0c
Create Date: 2026-01-19 16:01:54.855062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e2354fdd4d7'
down_revision: Union[str, Sequence[str], None] = '82c36cf03a0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_changed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_changed_at')
    # ### end Alembic commands ###
